export const formFields = {
  signUp: {
    username: {
      placeholder: '好きなユーザーネームを入力',
      isRequired: true,
      label: 'ユーザー名',
      order: 1,
    },
    email: {
      placeholder: 'email@example.com',
      isRequired: true,
      label: 'Eメール',
      order: 2,
    },
    password: {
      placeholder: '8文字以上のパスワード',
      isRequired: true,
      label: 'パスワード',
      order: 3,
    },
    confirm_password: {
      placeholder: '8文字以上のパスワード',
      isRequired: true,
      label: 'パスワード（確認用）',
      order: 4,
    },
  },
  confirmSignUp: {
    confirmation_code: {
      placeholder: '確認コードを入力',
      label: '',
    },
  },
};

export const dict = {
  ja: {
    'Sign in': 'ログイン',
    'Sign In': 'ログイン',
    'Signing In': 'ログイン中',
    'Creating account': 'アカウント作成中',
    'Creating Account': 'アカウント作成中',
    'Sign Out': 'サインアウト',
    'Create Account': 'アカウントを作成',
    'Incorrect username or password.': 'ユーザーネームかパスワードが正しくありません',
    'Password must have at least 8 characters': '8文字以上で入力してください',
    'Your passwords must match': 'パスワードが一致しません',
    'Forgot your password?': 'パスワードをお忘れですか？',
    'Reset Password': 'パスワードリセット',
    'Enter your username': 'ユーザーネーム',
    'Username/client id combination not found.': 'ユーザーが見つかりません',
    'User does not exist.': 'ユーザーが見つかりません',
    'Send code': 'リセットする',
    'Back to Sign In': 'ログインはこちら',
    'Email Address *': 'メール *',
    'Phone Number *': '電話番号 *',
    'Enter your password': 'パスワードを入力',
    'Enter your code': '確認コードを入力',
    'No account?': 'アカウントが未登録ですか？',
    'Reset password': 'パスワードをリセット',
    'User does not exist': 'ユーザーが存在しません',
    'User already exists': 'ユーザーは既に存在します',
    'Invalid password format': 'パスワードのフォーマットが不正です',
    'Create account': 'アカウントを作成',
    'Forgot Password': 'パスワードを忘れた',
    'Change Password': 'パスワードを変更',
    'New Password': '新しいパスワード',
    'Phone Number': '電話番号',
    'Confirm a Code': 'コードを確認',
    'Confirm Sign In': 'サインインを確認',
    'Confirm Sign up': 'サインアップを確認',
    'Send Code': 'コードを送信',
    Confirm: '確認',
    'Resend Code': 'コードを再送',
    Submit: '送信',
    Skip: 'スキップ',
    Verify: '検証',
    'Verify Contact': '連絡先を検証',
    Code: 'Code',
    'Confirmation Code': '確認コード',
    'Lost your code?': 'コードがありませんか？',
    'Account recovery requires verified contact information':
      'Account recovery requires verified contact information',
    'Invalid phone number format':
      '不正な電話番号フォーマットです。 電話番号は次のフォーマットで入力してください: +12345678900',
    'Have an account?': 'アカウントをお持ちですか？',
    'Create a new account': '新しいアカウントを作成',
    'Reset your password': 'パスワードをリセット',
    'Email Address': 'メール',
    'An account with the given email already exists.': 'そのメールアドレスは既に存在します',
    'Username cannot be empty': 'ユーザー名は必須です',
    'Password attempts exceeded': 'パスワード試行回数が超過しました',
    'We Emailed You': '確認メールを送信しました',
    'Your code is on the way. To log in, enter the code we emailed to':
      '入力されたメールアドレスに記載のあるコードを入力してください。受信に時間がかかる場合があります。',
    '. It may take a minute to arrive.': '受信に時間がかかる場合があります。',
    'Invalid verification code provided, please try again.':
      'コードが無効です。メール内容を再度確認するか、コードを再送してもう一度お試しください。',
  },
};
