import Head from 'next/head';
import { GetStaticPaths, GetStaticProps } from 'next';
import { Articles as ArticlesLayout } from '@/layouts/articles';
import type { Props as ArticlesProps } from '@/layouts/articles/types';
import { getArticle } from '@/utils';

export default function Articles(props: ArticlesProps) {
  const { articles } = props;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/site-icon-black.svg" />
      </Head>
      <main>
        <ArticlesLayout articles={articles} />
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  const id = context.params?.id;
  const article = await getArticle(id);

  return {
    props: {
      articles: article,
    },
  };
};

export const getStaticPaths: GetStaticPaths = () => {
  return { paths: [{ params: { id: '8362' } }, { params: { id: '5345' } }], fallback: false };
};
